### ISSUE TITLE
The CI improvements we need [tracking issue]

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/graphql#1886]
### Goal
The process of drafting and publishing a new release (with high quality confidence) should take no more than 2-3 hours.

**Current Problems**
1. QA Bottlenecks: too much manual QA that happens too infrequently (and mostly only when ready for release process)
2. Misc tasks-required-to-release Bottlenecks: merged PRs often produce other task requirements to complete before release (e.g. new docs or updates to existing, manual QA tests, Release Note copy e.g. Upgrade Instructions or Breaking explanations)
3. David P.: I’ve become the keeper of QA and to-dos related to each release, which makes me the bottleneck

**Improvements and Solutions**
1. Improve the integrity of each PR (add Cypress E2E check) and add additional CI automation (e.g. deploy)
2. Improve the process when meging PRs: e.g. better organization + communication amongst maintainers 
3. Collaboration: improve documentation and figure out the collaborative tools to use

## Cypress E2E runner
Current Cypress test covers Tutorial parts 1 - 6. It's available to run manually against either the current branch or against a specific project using the packages installed in the project:
- Script: https://github.com/redwoodjs/redwood/blob/main/tasks/test-tutorial
- Directory: https://github.com/redwoodjs/redwood/tree/main/tasks/e2e

> note: I'm not convinced we need to add _every_ part of Tutorial I and Tutorial II. But we do need to make sure each functional element is working.
 
**Improvements**
- [x] Create a GitHub Action to run Cypress as a required PR Check
- [x] matrix run: Node and OS [Windows, Linux]
    - currently only targeting Node v14; need to add 16 sometime before October
    - need to add Windows to E2E
- [x] test CSS styling on Scaffold UI (this was almost missed last time; currently requires manually watching runner)
- [ ] test misc CLI commands, e.g.: `dataMigrate`, `setup auth [netlify]`, `setup deploy [netlify]` (note: just need to confirm commands run and complete; not sure if we need to then test functionality of each at this point)

## Test and Storybook Commands
For full automation, ideally, we would create a project using the E2E runner. If passing, we would then run these checks:
- [x] Test: run `rw test` against a project that has passing Web and API tests
- [x] Storybook: run `rw storybook` against a project with Cells, pages, Layout, etc. and then use Cypress to confirm one of each component is displaying correctly (including states for Cells)

## Prerender
Need to determine testing for pretender. Both during dev and deploy:
- [x] TO DO

## Next Priorities (additions to original list)
- [ ] E2E Test Cleanup: #1835
- [x] remove Trigger on Push to Main: #1949
- [ ] CI: integrate ts-to-js transpiling within CRWA script: #1954
- [x] Add Logger to E2E (@dthyresson )
- [x]  add CI for `yarn rw serve`
- [ ] Add `db seed` to E2E
- [x] Consider using [RenovateBot](https://www.whitesourcesoftware.com/free-developer-tools/renovate) instead of Dependabot
- [ ] Storybook + Cypress: how to integrate this v6.3 feature --> https://medium.com/storybookjs/testing-lib-storybook-react-8c36716fab86

## Deployment + API/DB Connection
I'm currently running manual Netlify and Vercel deploys, which requires 1) checking build logs for _clean_ build and 2) checking deployed site to confirm API connection and DB are working accordingly.

We need to automate deploy and API/DB tests:
- when canaries are published, could trigger a workflow to install, modify, and deploy a project (note: modification needs to be automated as well for consistency across a growing number of deploy targets)
- would need DBs and, likely, resetting a DB before each deploy
- use Pingdom or some other cron tasks to consistently check API endpoints
- alerts+notifications: recommend create a notification channel in the Core Team's Slack Workspace

## Release Notes
At this time, I don't believe we need specific automation for drafting the Release Notes themselves. We have a good process, and manually reviewing and writing feels like helpful practice at this point in the project.

What would be helpful is consolidating _where_ we draft Release Notes and possibly automating distribution (e.g. GitHub, Forums, and Twitter). 
- [ ] needs discussion

# Why do PR checks take so much time to complete?
We currently have the following PR checks:
- `yarn install`
- `yarn build`
- `yarn lint`
- `yarn test`

And we run a matrix against Node.js [v12, v14] && OS [Windows, Linux]. So there are 4 runners in parallel.

Linux runners complete in 3-4 minutes. ✅
Windows runners complete in 9-10 minutes. ⛔️

Why, Windows? WHY?

## TS
TS build takes time. It's not terrible though

## Windows: Caching and Connection Timeouts
Take a look at a [Windows run](https://github.com/redwoodjs/redwood/runs/1994304838?check_suite_focus=true), which is often around 10 minutes in total. The bulk of the time (4 minutes) is `yarn install` with the `yarn build` and `yarn test` tieing for 2nd place at 2 minutes.

### Windows `node_modules` cache is unreliable
We are able to use the GitHub Action `node_modules` cache on Linux. However, last time we tried the Windows cache was unreliable and would often have false negatives when checking if cache needed to be updated -- this led to stale `node_modules` being used, which threw confusing errors (e.g. if a package was added or upgraded, the runner wouldn't be using the latest).

However, even without the cache, I was surprised to find out the real problem adding to total time is a connection error.

### "There appears to be trouble with your network connection..."
I've watched and timed the installation process, and it turns out a connection error takes 1-2 minutes of time per installation:
```bash
info There appears to be trouble with your network connection. Retrying...
```
You can see it here:
<img width="605" alt="Screen Shot 2021-02-27 at 12 57 51 PM" src="https://user-images.githubusercontent.com/2951/109400104-96f9a680-78fb-11eb-8e8e-96314d3b20a4.png">

About 3-4 months ago, I spent at least 4 hours attempting to diagnose and resolve this connection error. Unsuccessfully. I determined it was either a bug with Yarn on Windows _or_ it's an issue with GitHub's networking for the Windows runners. 

I owe 🍻 to whoever can figure this one out.

**Comment by thedavidprice** [comment]
I intentionally left out the topic of "Performance: Benchmarks and Checks". I have some ideas and examples to draw from. For me, this feels like the next step _after_ the kinds of CI improvements I mentioned above.

**Comment by Tobbe** [comment]
Regarding Windows

I'm seeing `info There appears to be trouble with your network connection. Retrying...` too, when running locally on Windows. I've just always assumed it was an actual problem with my flaky connection.

Windows' file system is slower than Linux's, so when reading or writing lots of small files, Windows is going to see a lot worse performance than Linux. And guess what `yarn install` is doing...

Googling around a bit, I found this thread https://travis-ci.community/t/yarn-network-troubles/333 The suggest disabling Windows Defender. Combining the info there, with these Windows Defender instructions for Github Actions could be worth exploring. https://github.com/actions/virtual-environments/issues/855

**Comment by peterp** [comment]
Here's my e2e (cypress) GitHub workflow:

```
name: E2E Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Migrate test database
        run: yarn rw prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres

      - name: Start server in background
        run: yarn rw dev &
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wait-on: 'http://localhost:8910'
          record: true
          working-directory: scripts/e2e
```
